version: '3.8'
services:
  backend:
    build: ./backend
    container_name: 'backend'
    ports:
      - 8380:8380
    volumes:
      - ./backend:/app
    depends_on:
      - db1
      - db2
  db1:
    image: postgres:15
    restart: always
    container_name: 'db1'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    volumes:
      - db1_volume:/var/lib/postgresql/data
  
  db2:
    image: postgres:15
    restart: always
    container_name: 'db2'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    volumes:
      - db2_volume:/var/lib/postgresql/data

volumes:
  db1_volume:
  db2_volume:
