version: '3.8'
services:
  backend:
    build: ./backend
    container_name: 'backend'
    environment:
      - DB1_URL=postgresql://postgres:root@db1:5432/db
      - DB2_URL=postgresql://postgres:root@db2:5432/db
    ports:
      - 8380:8380
    volumes:
      - ./backend:/app
    depends_on:
      - db1
      - db2
    networks:
      - app_net

  db1:
    image: postgres:15
    restart: always
    container_name: 'db1'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    volumes:
      - db_1:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app_net

  db2:
    image: postgres:15
    restart: always
    container_name: 'db2'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    volumes:
      - db_2:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app_net

networks:
  app_net:

volumes:
  db_1:
  db_2:
