version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: 'app-frontend'
    environment:
      - API_URL=http://backend:8380
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
    networks:
      - app_net

  backend:
    build: ./backend
    container_name: 'app-backend'
    environment:
      - DB_URL=postgresql://postgres:root@database:5432/db?sslmode=disable
    ports:
      - 8380:8380
    volumes:
      - ./backend:/app
    depends_on:
      - database
    networks:
      - app_net

  database:
    image: postgres:15
    restart: always
    container_name: 'app-database'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=task-list
    volumes:
      - database:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app_net

networks:
  app_net:

volumes:
  database:
